import type { NextPage } from "next";
import Head from "next/head";
import { Gallery } from "../components/Gallery";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Galleria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Gallery />
    </div>
  );
};

export default Home;
